# Generated by Django 5.0.7 on 2025-10-02 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Domain must be in format: yourname.listacross.eu', regex='^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.listacross\\.eu$')], verbose_name='domain name'),
        ),
    ]
