@echo off
echo Changing to frontend directory...
cd /d "C:\projects\listacrosseu\frontend"
echo Current directory: %CD%
echo Listing package.json...
dir package.json
echo Starting npm dev server...
npm run dev