import Link from 'next/link';
import SearchBoxNew from '@/components/SearchBoxNew';

type Lang = "en" | "nl" | "pt" | "fr" | "de" | "es";

const T = {
  en: {
    trustBadge: "🌟 Trusted by 50,000+ European businesses",
    heroTitle: "Find Businesses",
    heroTitleGradient: "Across Europe",
    heroSubtitle: "Discover millions of businesses across 30+ European countries. From restaurants in Paris to tech companies in Amsterdam.",
    searchButton: "Start Searching Now",
    pricingButton: "View Pricing Plans",
    featuredTitle: "Featured Businesses",
    featuredSubtitle: "Discover top-rated businesses across Europe",
    categoriesTitle: "Popular Categories",
    categoriesSubtitle: "Browse by business type",
    seeAllCategories: "See All Categories",
    getStartedTitle: "Ready to Get Started?",
    getStartedSubtitle: "Join thousands of businesses and customers connecting across Europe",
    businessesText: "businesses",
    whyChooseTitle: "Why Choose ListAcross EU?",
    whyChooseSubtitle: "The most comprehensive European business directory",
    europeWideCoverage: "Europe-Wide Coverage",
    europeWideCoverageDesc: "Search across 30+ European countries with comprehensive coverage of local businesses, from major cities to small towns.",
    smartSearch: "Smart Search Technology",
    smartSearchDesc: "Advanced AI-powered search with instant suggestions, multilingual support, and intelligent filtering for precise results.",
    verifiedTrusted: "Verified & Trusted",
    verifiedTrustedDesc: "All business listings are verified with up-to-date contact information, reviews, and ratings from the European community.",
    restaurants: "Restaurants",
    hotels: "Hotels",
    technology: "Technology",
    healthcare: "Healthcare",
    retail: "Retail",
    services: "Services"
  },
  nl: {
    trustBadge: "🌟 Vertrouwd door 50.000+ Europese bedrijven",
    heroTitle: "Vind Bedrijven",
    heroTitleGradient: "Door Europa",
    heroSubtitle: "Ontdek miljoenen bedrijven in 30+ Europese landen. Van restaurants in Parijs tot techbedrijven in Amsterdam.",
    searchButton: "Begin Nu Met Zoeken",
    pricingButton: "Bekijk Prijzen",
    featuredTitle: "Uitgelichte Bedrijven",
    featuredSubtitle: "Ontdek topgewaardeerde bedrijven in Europa",
    categoriesTitle: "Populaire Categorieën",
    categoriesSubtitle: "Bladeren op bedrijfstype",
    seeAllCategories: "Alle Categorieën Zien",
    getStartedTitle: "Klaar om te Beginnen?",
    getStartedSubtitle: "Sluit je aan bij duizenden bedrijven en klanten die verbinden in Europa",
    businessesText: "bedrijven",
    whyChooseTitle: "Waarom Kiezen Voor ListAcross EU?",
    whyChooseSubtitle: "De meest uitgebreide Europese bedrijvengids",
    europeWideCoverage: "Europa-brede Dekking",
    europeWideCoverageDesc: "Zoek in 30+ Europese landen met uitgebreide dekking van lokale bedrijven, van grote steden tot kleine dorpen.",
    smartSearch: "Slimme Zoektechnologie",
    smartSearchDesc: "Geavanceerd AI-aangedreven zoeken met directe suggesties, meertalige ondersteuning en intelligente filtering voor precieze resultaten.",
    verifiedTrusted: "Geverifieerd & Vertrouwd",
    verifiedTrustedDesc: "Alle bedrijfslijsten zijn geverifieerd met actuele contactinformatie, beoordelingen en ratings van de Europese gemeenschap.",
    restaurants: "Restaurants",
    hotels: "Hotels",
    technology: "Technologie",
    healthcare: "Gezondheidszorg",
    retail: "Detailhandel",
    services: "Diensten"
  },
  pt: {
    trustBadge: "🌟 Confiado por 50.000+ empresas europeias",
    heroTitle: "Encontre Empresas",
    heroTitleGradient: "Por Toda Europa",
    heroSubtitle: "Descubra milhões de empresas em 30+ países europeus. De restaurantes em Paris a empresas de tecnologia em Amsterdam.",
    searchButton: "Comece a Pesquisar Agora",
    pricingButton: "Ver Planos de Preços",
    featuredTitle: "Empresas em Destaque",
    featuredSubtitle: "Descubra empresas com melhor classificação na Europa",
    categoriesTitle: "Categorias Populares",
    categoriesSubtitle: "Navegar por tipo de empresa",
    seeAllCategories: "Ver Todas as Categorias",
    getStartedTitle: "Pronto para Começar?",
    getStartedSubtitle: "Junte-se a milhares de empresas e clientes conectando-se pela Europa",
    businessesText: "empresas",
    whyChooseTitle: "Por Que Escolher ListAcross EU?",
    whyChooseSubtitle: "O diretório europeu de empresas mais abrangente",
    europeWideCoverage: "Cobertura em Toda a Europa",
    europeWideCoverageDesc: "Pesquise em 30+ países europeus com cobertura abrangente de empresas locais, desde grandes cidades até pequenas vilas.",
    smartSearch: "Tecnologia de Pesquisa Inteligente",
    smartSearchDesc: "Pesquisa avançada alimentada por IA com sugestões instantâneas, suporte multilíngue e filtragem inteligente para resultados precisos.",
    verifiedTrusted: "Verificado e Confiável",
    verifiedTrustedDesc: "Todas as listagens de empresas são verificadas com informações de contato atualizadas, avaliações e classificações da comunidade europeia.",
    restaurants: "Restaurantes",
    hotels: "Hotéis",
    technology: "Tecnologia",
    healthcare: "Saúde",
    retail: "Varejo",
    services: "Serviços"
  },
  fr: {
    trustBadge: "🌟 Fait confiance par 50 000+ entreprises européennes",
    heroTitle: "Trouvez des Entreprises",
    heroTitleGradient: "À Travers l'Europe",
    heroSubtitle: "Découvrez des millions d'entreprises dans 30+ pays européens. Des restaurants à Paris aux entreprises tech d'Amsterdam.",
    searchButton: "Commencer la Recherche",
    pricingButton: "Voir les Plans Tarifaires",
    featuredTitle: "Entreprises en Vedette",
    featuredSubtitle: "Découvrez les entreprises les mieux notées d'Europe",
    categoriesTitle: "Catégories Populaires",
    categoriesSubtitle: "Parcourir par type d'entreprise",
    seeAllCategories: "Voir Toutes les Catégories",
    getStartedTitle: "Prêt à Commencer?",
    getStartedSubtitle: "Rejoignez des milliers d'entreprises et clients qui se connectent à travers l'Europe",
    businessesText: "entreprises",
    whyChooseTitle: "Pourquoi Choisir ListAcross EU?",
    whyChooseSubtitle: "L'annuaire d'entreprises européennes le plus complet",
    europeWideCoverage: "Couverture Paneuropéenne",
    europeWideCoverageDesc: "Recherchez dans 30+ pays européens avec une couverture complète des entreprises locales, des grandes villes aux petites communes.",
    smartSearch: "Technologie de Recherche Intelligente",
    smartSearchDesc: "Recherche avancée alimentée par IA avec suggestions instantanées, support multilingue et filtrage intelligent pour des résultats précis.",
    verifiedTrusted: "Vérifié et Fiable",
    verifiedTrustedDesc: "Tous les listings d'entreprises sont vérifiés avec des informations de contact à jour, des avis et évaluations de la communauté européenne.",
    restaurants: "Restaurants",
    hotels: "Hôtels",
    technology: "Technologie",
    healthcare: "Santé",
    retail: "Commerce",
    services: "Services"
  },
  de: {
    trustBadge: "🌟 Vertraut von 50.000+ europäischen Unternehmen",
    heroTitle: "Finde Unternehmen",
    heroTitleGradient: "Quer durch Europa",
    heroSubtitle: "Entdecke Millionen von Unternehmen in 30+ europäischen Ländern. Von Restaurants in Paris bis zu Tech-Unternehmen in Amsterdam.",
    searchButton: "Jetzt Suchen Starten",
    pricingButton: "Preispläne Anzeigen",
    featuredTitle: "Ausgewählte Unternehmen",
    featuredSubtitle: "Entdecke bestbewertete Unternehmen in Europa",
    categoriesTitle: "Beliebte Kategorien",
    categoriesSubtitle: "Nach Unternehmenstyp durchsuchen",
    seeAllCategories: "Alle Kategorien Anzeigen",
    getStartedTitle: "Bereit Anzufangen?",
    getStartedSubtitle: "Schließen Sie sich Tausenden von Unternehmen und Kunden an, die sich in Europa vernetzen",
    businessesText: "unternehmen",
    whyChooseTitle: "Warum ListAcross EU Wählen?",
    whyChooseSubtitle: "Das umfassendste europäische Unternehmensverzeichnis",
    europeWideCoverage: "Europaweite Abdeckung",
    europeWideCoverageDesc: "Suchen Sie in 30+ europäischen Ländern mit umfassender Abdeckung lokaler Unternehmen, von Großstädten bis zu kleinen Gemeinden.",
    smartSearch: "Intelligente Suchtechnologie",
    smartSearchDesc: "Erweiterte KI-gesteuerte Suche mit sofortigen Vorschlägen, mehrsprachiger Unterstützung und intelligenter Filterung für präzise Ergebnisse.",
    verifiedTrusted: "Verifiziert & Vertrauenswürdig",
    verifiedTrustedDesc: "Alle Unternehmenseinträge sind mit aktuellen Kontaktinformationen, Bewertungen und Ratings der europäischen Gemeinschaft verifiziert.",
    restaurants: "Restaurants",
    hotels: "Hotels",
    technology: "Technologie",
    healthcare: "Gesundheitswesen",
    retail: "Einzelhandel",
    services: "Dienstleistungen"
  },
  es: {
    trustBadge: "🌟 Confiado por 50,000+ empresas europeas",
    heroTitle: "Encuentra Empresas",
    heroTitleGradient: "Por Toda Europa", 
    heroSubtitle: "Descubre millones de empresas en 30+ países europeos. Desde restaurantes en París hasta empresas tech en Ámsterdam.",
    searchButton: "Empezar Búsqueda Ahora",
    pricingButton: "Ver Planes de Precios",
    featuredTitle: "Empresas Destacadas",
    featuredSubtitle: "Descubre empresas mejor valoradas de Europa",
    categoriesTitle: "Categorías Populares",
    categoriesSubtitle: "Navegar por tipo de empresa",
    seeAllCategories: "Ver Todas las Categorías",
    getStartedTitle: "¿Listo para Empezar?",
    getStartedSubtitle: "Únete a miles de empresas y clientes conectándose por Europa",
    businessesText: "empresas",
    whyChooseTitle: "¿Por Qué Elegir ListAcross EU?",
    whyChooseSubtitle: "El directorio empresarial europeo más completo",
    europeWideCoverage: "Cobertura Paneuropea",
    europeWideCoverageDesc: "Busca en 30+ países europeos con cobertura completa de empresas locales, desde grandes ciudades hasta pueblos pequeños.",
    smartSearch: "Tecnología de Búsqueda Inteligente",
    smartSearchDesc: "Búsqueda avanzada impulsada por IA con sugerencias instantáneas, soporte multiidioma y filtrado inteligente para resultados precisos.",
    verifiedTrusted: "Verificado y Confiable",
    verifiedTrustedDesc: "Todos los listados empresariales están verificados con información de contacto actualizada, reseñas y calificaciones de la comunidad europea.",
    restaurants: "Restaurantes",
    hotels: "Hoteles",
    technology: "Tecnología",
    healthcare: "Salud",
    retail: "Comercio",
    services: "Servicios"
  }
} as const;

// Continue with rest of the file...