# Generated by Django 5.0.7 on 2025-10-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Generated or uploaded image for the article', upload_to='travel_images/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('generated_by_ai', models.BooleanField(default=True, verbose_name='generated by AI')),
                ('generation_prompt', models.TextField(blank=True, verbose_name='generation prompt')),
                ('generation_style', models.CharField(blank=True, max_length=50, verbose_name='generation style')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['order', '-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['article', 'is_featured'], name='travel_arti_article_24e63b_idx'), models.Index(fields=['article', 'order'], name='travel_arti_article_37d2af_idx')],
            },
        ),
    ]
