# Generated by Django 5.0.7 on 2025-10-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_articleimage'),
    ]

    operations = [
    ]
