# Generated by Django 5.2.7 on 2025-11-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ListAcross EU', max_length=100)),
                ('site_description', models.TextField(default='The premier business directory for European markets')),
                ('contact_email', models.EmailField(default='contact@listacrosseu.com', max_length=254)),
                ('support_email', models.EmailField(default='support@listacrosseu.com', max_length=254)),
                ('default_language', models.CharField(default='eu', max_length=5)),
                ('enable_registration', models.BooleanField(default=True)),
                ('enable_comments', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, site shows maintenance page to non-admin users')),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics or other tracking code')),
                ('logo', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
                ('footer_logo', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('default_title', models.CharField(blank=True, max_length=200)),
                ('default_description', models.TextField(blank=True)),
                ('default_keywords', models.TextField(blank=True)),
                ('og_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
