# Generated by Django 5.2.7 on 2025-11-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_star_animation',
            field=models.BooleanField(default=True, help_text='Enable animated EU stars on hero section'),
        ),
    ]
