# Generated by Django 5.2.7 on 2025-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ListAcrossEU', max_length=200)),
                ('site_tagline', models.CharField(default='European Business Directory', max_length=500)),
                ('contact_email', models.EmailField(default='contact@listacrosseu.com', max_length=254)),
                ('support_email', models.EmailField(default='support@listacrosseu.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('address', models.TextField(default='Brussels, Belgium')),
                ('logo', models.ImageField(blank=True, help_text='Site logo - PNG or SVG recommended, max 2MB, 200x200px', null=True, upload_to='site/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon - ICO or PNG, 16x16 or 32x32px', null=True, upload_to='site/favicons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
