# Generated by Django 5.2.7 on 2025-11-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='navigation_display_mode',
            field=models.CharField(choices=[('flags', 'Flags Only'), ('names', 'Names Only'), ('both', 'Flags and Names')], default='both', help_text='How to display language selector in navigation', max_length=10),
        ),
    ]
