# Generated by Django 5.2.7 on 2025-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesetting_navigation_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_nav_animation',
            field=models.BooleanField(default=True, help_text='Enable animated border under navigation'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_slideshow_animation',
            field=models.BooleanField(default=True, help_text='Enable slideshow animations on homepage'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_animation_colors',
            field=models.CharField(default='from-blue-500 via-purple-500 to-indigo-500', help_text='Tailwind gradient colors for navigation border animation', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_animation_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', help_text='Speed of navigation border animation', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='slideshow_animation_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', help_text='Speed of slideshow animations', max_length=10),
        ),
    ]
