# Generated by Django 5.2.7 on 2025-10-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('free', 'Free'), ('product', 'Product Page'), ('premium', 'Premium')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('entitlements', models.JSONField(default=dict)),
                ('highlights', models.JSONField(default=list)),
                ('priority_weight', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_in_sitemap', models.BooleanField(default=True)),
                ('force_noindex', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('featured_weight', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan')),
            ],
        ),
    ]
