# Generated by Django 5.2.7 on 2025-11-05 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters. This appears as the clickable headline in search results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Recommended: 120-160 characters. This appears as the snippet under the title in search results.', max_length=160, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Use to specify the preferred URL for this page to prevent duplicate content issues.', verbose_name='Canonical URL')),
                ('robots', models.CharField(blank=True, default='index,follow', help_text='Controls how search engines crawl this page. Common values: index,follow | noindex,nofollow | index,nofollow', max_length=50, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, help_text='Title when shared on social media. Falls back to meta_title if empty.', max_length=120, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description when shared on social media. Falls back to meta_description if empty.', max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.URLField(blank=True, help_text='Image when shared on social media. Recommended size: 1200x630px.', verbose_name='Open Graph Image')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_fr', models.CharField(blank=True, max_length=100, verbose_name='Name (French)')),
                ('name_nl', models.CharField(blank=True, max_length=100, verbose_name='Name (Dutch)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)')),
                ('name_de', models.CharField(blank=True, max_length=100, verbose_name='Name (German)')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters. This appears as the clickable headline in search results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Recommended: 120-160 characters. This appears as the snippet under the title in search results.', max_length=160, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Use to specify the preferred URL for this page to prevent duplicate content issues.', verbose_name='Canonical URL')),
                ('robots', models.CharField(blank=True, default='index,follow', help_text='Controls how search engines crawl this page. Common values: index,follow | noindex,nofollow | index,nofollow', max_length=50, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, help_text='Title when shared on social media. Falls back to meta_title if empty.', max_length=120, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description when shared on social media. Falls back to meta_description if empty.', max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.URLField(blank=True, help_text='Image when shared on social media. Recommended size: 1200x630px.', verbose_name='Open Graph Image')),
                ('name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (French)')),
                ('description_nl', models.TextField(blank=True, verbose_name='Description (Dutch)')),
                ('description_pt', models.TextField(blank=True, verbose_name='Description (Portuguese)')),
                ('description_de', models.TextField(blank=True, verbose_name='Description (German)')),
                ('description_es', models.TextField(blank=True, verbose_name='Description (Spanish)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_images/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.business')),
            ],
            options={
                'verbose_name': 'Business Image',
                'verbose_name_plural': 'Business Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
