# Generated by Django 5.2.7 on 2025-11-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_seo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='csv_import_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CSV Import Date'),
        ),
        migrations.AddField(
            model_name='business',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Friday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='imported_from_csv',
            field=models.BooleanField(default=False, verbose_name='Imported from CSV'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
        migrations.AddField(
            model_name='business',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saturday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sunday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thursday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuesday Hours'),
        ),
        migrations.AddField(
            model_name='business',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wednesday Hours'),
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/', verbose_name='CSV File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Processing Status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Processed Rows')),
                ('successful_rows', models.PositiveIntegerField(default=0, verbose_name='Successful Rows')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='Failed Rows')),
                ('error_log', models.TextField(blank=True, verbose_name='Error Log')),
                ('processing_notes', models.TextField(blank=True, verbose_name='Processing Notes')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'CSV Upload',
                'verbose_name_plural': 'CSV Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
