# Generated by Django 5.2.7 on 2025-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_business_csv_import_date_business_friday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_import_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Google Import Date'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Place ID'),
        ),
    ]
