# Generated by Django 5.2.7 on 2025-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('og_image', models.URLField(blank=True, help_text='Absolute URL to social/OG image.')),
                ('meta_json', models.JSONField(blank=True, help_text='Arbitrary JSON for extra meta / JSON-LD.', null=True)),
                ('slug', models.SlugField(max_length=160)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=5)),
                ('is_published', models.BooleanField(default=True)),
                ('template_key', models.CharField(blank=True, help_text='Optional template identifier.', max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, help_text='HTML or Markdown content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'language', 'is_published'], name='cms_page_slug_ab0511_idx')],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
