# Generated by Django 4.2.7 on 2025-10-02 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='business name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='short description')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='business_covers/')),
                ('monday_hours', models.CharField(blank=True, max_length=50, verbose_name='Monday hours')),
                ('tuesday_hours', models.CharField(blank=True, max_length=50, verbose_name='Tuesday hours')),
                ('wednesday_hours', models.CharField(blank=True, max_length=50, verbose_name='Wednesday hours')),
                ('thursday_hours', models.CharField(blank=True, max_length=50, verbose_name='Thursday hours')),
                ('friday_hours', models.CharField(blank=True, max_length=50, verbose_name='Friday hours')),
                ('saturday_hours', models.CharField(blank=True, max_length=50, verbose_name='Saturday hours')),
                ('sunday_hours', models.CharField(blank=True, max_length=50, verbose_name='Sunday hours')),
                ('plan', models.CharField(choices=[('free', 'Free Listing'), ('local', 'Local Plan'), ('country', 'Country Plan'), ('eu', 'EU Plan')], default='free', max_length=20, verbose_name='plan')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='keywords')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='clicks count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
                ('flag_image', models.ImageField(blank=True, upload_to='flags/')),
                ('is_eu_member', models.BooleanField(default=True, verbose_name='is EU member')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='population')),
                ('is_capital', models.BooleanField(default=False, verbose_name='is capital')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='businesses.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country__name', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='businesses.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_images/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Image',
                'verbose_name_plural': 'Business Images',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='businesses.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='businesses.city'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='subcategories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__isnull': False}, related_name='subcategory_businesses', to='businesses.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='moderation notes')),
                ('owner_response', models.TextField(blank=True, verbose_name='owner response')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='response date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'reviewer')},
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'plan'], name='businesses__status_a501f4_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city', 'category'], name='businesses__city_id_55e238_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['featured', 'verified'], name='businesses__feature_3f8295_idx'),
        ),
    ]
