# Generated by Django 5.0.7 on 2025-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessclaim_businessregistration_businessphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
