# Generated by Django 5.0.7 on 2025-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_add_city_slug_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
