# Generated by Django 5.0.7 on 2025-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_add_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country'), ('slug', 'country')},
        ),
    ]
