# Generated by Django 4.2.7 on 2025-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_add_duplicate_prevention_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_business_name_city',
        ),
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_business_email_city',
        ),
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_business_phone_city',
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_business_name_city'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email', 'city'), name='unique_business_email_city'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone', 'city'), name='unique_business_phone_city'),
        ),
    ]
