# Generated by Django 5.2.7 on 2025-10-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_add_duplicate_prevention_constraints'),
    ]

    operations = [
    ]
