# Generated by Django 5.2.7 on 2025-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_auto_20251031_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations for 27 EU languages', verbose_name='translations'),
        ),
    ]
