# Generated by Django 5.2.7 on 2025-11-05 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_on_dashboard', models.BooleanField(default=False, help_text='Enable Arabic language support on the dashboard', verbose_name='Arabic on Dashboard')),
                ('arabic_on_website', models.BooleanField(default=False, help_text='Enable Arabic language support on the public website', verbose_name='Arabic on Website')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('ar', 'Arabic')], default='en', help_text="User's preferred language for the interface", max_length=10, verbose_name='Preferred Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
