# Generated by Django 5.2.7 on 2025-11-05 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters. This appears as the clickable headline in search results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Recommended: 120-160 characters. This appears as the snippet under the title in search results.', max_length=160, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Use to specify the preferred URL for this page to prevent duplicate content issues.', verbose_name='Canonical URL')),
                ('robots', models.CharField(blank=True, default='index,follow', help_text='Controls how search engines crawl this page. Common values: index,follow | noindex,nofollow | index,nofollow', max_length=50, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, help_text='Title when shared on social media. Falls back to meta_title if empty.', max_length=120, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description when shared on social media. Falls back to meta_description if empty.', max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.URLField(blank=True, help_text='Image when shared on social media. Recommended size: 1200x630px.', verbose_name='Open Graph Image')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters. This appears as the clickable headline in search results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Recommended: 120-160 characters. This appears as the snippet under the title in search results.', max_length=160, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Use to specify the preferred URL for this page to prevent duplicate content issues.', verbose_name='Canonical URL')),
                ('robots', models.CharField(blank=True, default='index,follow', help_text='Controls how search engines crawl this page. Common values: index,follow | noindex,nofollow | index,nofollow', max_length=50, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, help_text='Title when shared on social media. Falls back to meta_title if empty.', max_length=120, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description when shared on social media. Falls back to meta_description if empty.', max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.URLField(blank=True, help_text='Image when shared on social media. Recommended size: 1200x630px.', verbose_name='Open Graph Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('cover_image', models.URLField(blank=True, verbose_name='Cover Image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
