# Generated by Django 5.2.7 on 2025-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name_en'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_fr',
            field=models.TextField(blank=True, default='', verbose_name='Description (French)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (Dutch)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_pt',
            field=models.TextField(blank=True, default='', verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (German)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Category Name (English)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (French)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (Dutch)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ar',
            field=models.TextField(blank=True, default='', verbose_name='Content (Arabic)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_de',
            field=models.TextField(blank=True, default='', verbose_name='Content (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(default='', verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(blank=True, default='', verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fr',
            field=models.TextField(blank=True, default='', verbose_name='Content (French)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_nl',
            field=models.TextField(blank=True, default='', verbose_name='Content (Dutch)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_pt',
            field=models.TextField(blank=True, default='', verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ar',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (Arabic)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_de',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (English)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_es',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (Spanish)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_fr',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (French)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_nl',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (Dutch)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_pt',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Excerpt (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (French)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_nl',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Dutch)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_pt',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Portuguese)'),
        ),
    ]
