# Generated by Django 5.2.7 on 2025-11-06 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('outline', 'Outline Generation'), ('draft', 'Draft Generation'), ('seo', 'SEO Generation'), ('translate', 'Translation')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
