# Generated by Django 4.2.7 on 2025-10-02 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('json', 'JSON File'), ('api', 'API Endpoint'), ('openstreetmap', 'OpenStreetMap'), ('google_places', 'Google Places'), ('yelp', 'Yelp API'), ('foursquare', 'Foursquare API')], max_length=20, verbose_name='source type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('endpoint_url', models.URLField(blank=True, verbose_name='endpoint URL')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API key')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='headers')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='data_imports/csv/')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='data_imports/json/')),
                ('field_mapping', models.JSONField(default=dict, help_text='Map source fields to our business model fields', verbose_name='field mapping')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20, verbose_name='status')),
                ('auto_import', models.BooleanField(default=False, verbose_name='auto import')),
                ('import_frequency', models.PositiveIntegerField(default=24, verbose_name='import frequency (hours)')),
                ('last_import', models.DateTimeField(blank=True, null=True, verbose_name='last import')),
                ('total_imported', models.PositiveIntegerField(default=0, verbose_name='total imported')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('mapping', models.JSONField(default=dict, help_text='JSON mapping of source fields to target fields', verbose_name='field mapping')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Mapping',
                'verbose_name_plural': 'Import Mappings',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='file path')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='file type')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='options')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='progress')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='total records')),
                ('processed_records', models.PositiveIntegerField(default=0, verbose_name='processed records')),
                ('successful_records', models.PositiveIntegerField(default=0, verbose_name='successful records')),
                ('failed_records', models.PositiveIntegerField(default=0, verbose_name='failed records')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('error_details', models.JSONField(blank=True, default=dict, verbose_name='error details')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_import.importmapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('json', 'JSON File'), ('api', 'API Endpoint'), ('openstreetmap', 'OpenStreetMap'), ('google_places', 'Google Places'), ('yelp', 'Yelp API'), ('foursquare', 'Foursquare API')], max_length=20, verbose_name='source type')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='field mapping')),
                ('validation_rules', models.JSONField(default=dict, verbose_name='validation rules')),
                ('transformation_rules', models.JSONField(default=dict, verbose_name='transformation rules')),
                ('sample_input', models.JSONField(blank=True, default=dict, verbose_name='sample input')),
                ('sample_output', models.JSONField(blank=True, default=dict, verbose_name='sample output')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Template',
                'verbose_name_plural': 'Data Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='source ID')),
                ('source_data', models.JSONField(default=dict, verbose_name='source data')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('duplicate', 'Duplicate')], max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='businesses.business')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_import.importjob')),
            ],
            options={
                'verbose_name': 'Import Record',
                'verbose_name_plural': 'Import Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_job', 'status'], name='data_import_import__57e597_idx'), models.Index(fields=['source_id'], name='data_import_source__1a909e_idx')],
            },
        ),
    ]
