# Generated by Django 5.2.7 on 2025-11-01 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('default_lang', models.CharField(default='en', max_length=2, validators=[django.core.validators.RegexValidator(message='Use 2-letter lang codes, e.g., en, nl, fr, es, pt.', regex='^[a-z]{2}$')])),
                ('supported_langs', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('guardrails', models.JSONField(blank=True, default=dict)),
                ('cta_text', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assistant Configuration',
                'verbose_name_plural': 'Assistant Configurations',
            },
        ),
    ]
