# Generated by Django 5.2.7 on 2025-11-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assistant_studio.assistantconfig')),
            ],
            options={
                'ordering': ('-version',),
                'unique_together': {('config', 'version')},
            },
        ),
    ]
