# Generated by Django 5.2.7 on 2025-11-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_studio', '0002_assistantversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('kb_json', 'KB JSON'), ('blog_md', 'Blog Markdown'), ('pricing_json', 'Pricing JSON'), ('faq_md', 'FAQ Markdown'), ('external_url', 'External URL')], default='kb_json', max_length=20)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('source_path', models.CharField(blank=True, default='', max_length=300)),
                ('url', models.URLField(blank=True, default='')),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-enabled', '-priority', 'slug'),
            },
        ),
    ]
