# Generated by Django 5.2.7 on 2025-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_studio', '0003_knowledgedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('answer_style', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], default='short', max_length=12)),
                ('primary_cta', models.CharField(choices=[('create_listing', 'Create Listing'), ('upgrade_plan', 'Upgrade Plan'), ('start_jcw_build', 'Start JCW Build'), ('start_print_order', 'Start Print Order'), ('none', 'None')], default='none', max_length=40)),
                ('fallback_doc_slugs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-enabled', '-priority', 'name'),
            },
        ),
    ]
