# Generated by Django 5.2.7 on 2025-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ListAcross EU', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(verbose_name='Site Description')),
                ('default_meta_title', models.CharField(max_length=200, verbose_name='Default Meta Title')),
                ('default_meta_description', models.CharField(max_length=300, verbose_name='Default Meta Description')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=20, verbose_name='Google Tag Manager ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
