# Generated by Django for counter triggers

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        # Triggers disabled for SQLite compatibility - enable when using PostgreSQL
    ]