# Generated by Django 5.2.7 on 2025-11-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO-2 country code', max_length=2, primary_key=True, serialize=False)),
                ('names_json', models.JSONField(default=dict, help_text="Translations: {'en': 'Portugal', 'nl': 'Portugal', 'pt': 'Portugal'}")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Lowercase, ASCII, hyphenated', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Lowercase, ASCII, hyphenated', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='geo.city')),
            ],
            options={
                'ordering': ['city', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
